// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfk6_h7gnV5fvgIiOaZ0-8ZRqrXkba-yg',
    appId: '1:78529643359:web:2bd145c2ec97b458fa6cea',
    messagingSenderId: '78529643359',
    projectId: 'urdesk-a1031',
    authDomain: 'urdesk-a1031.firebaseapp.com',
    storageBucket: 'urdesk-a1031.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYa9bA69JUTaB-d8PcP27LllabTfi3DA0',
    appId: '1:78529643359:android:d0b2aec6e02a8ad6fa6cea',
    messagingSenderId: '78529643359',
    projectId: 'urdesk-a1031',
    storageBucket: 'urdesk-a1031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DKIhtSw5LFi1aNvUKi9fINo76hkhtMg',
    appId: '1:78529643359:ios:eaffc7627207a6e9fa6cea',
    messagingSenderId: '78529643359',
    projectId: 'urdesk-a1031',
    storageBucket: 'urdesk-a1031.appspot.com',
    iosBundleId: 'com.example.urdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DKIhtSw5LFi1aNvUKi9fINo76hkhtMg',
    appId: '1:78529643359:ios:eaffc7627207a6e9fa6cea',
    messagingSenderId: '78529643359',
    projectId: 'urdesk-a1031',
    storageBucket: 'urdesk-a1031.appspot.com',
    iosBundleId: 'com.example.urdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfk6_h7gnV5fvgIiOaZ0-8ZRqrXkba-yg',
    appId: '1:78529643359:web:99178d384955e0bdfa6cea',
    messagingSenderId: '78529643359',
    projectId: 'urdesk-a1031',
    authDomain: 'urdesk-a1031.firebaseapp.com',
    storageBucket: 'urdesk-a1031.appspot.com',
  );
}
